version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3

    steps:
      - checkout

      - run:
          name: Run Custom Script
          command: |
            echo 'replace me with real tests!'
            false
