version: 2.1
orbs:
  android: circleci/android@0.2.1

jobs:
  # beta-ios:
  #   macos:
  #     xcode: 14.0.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run the script for beta iOS
  #         command: |
  #           bash scripts/prepare-flutter.sh
  #           bash scripts/prepare-ios.sh
  #           bash scripts/beta-ios.sh

  beta-android:
    docker:
      - image: currusci/flutter

    steps:
      - checkout
      - run: flutter doctor
      - run: flutter doctor
      - run: flutter build apk--release

      - run:
          name: Run the script for beta Android
          command: |
 

            bash scripts/beta-android.sh

workflows:
  build-test-adhoc:
    jobs:
      - beta-android
      # - beta-ios
