version: 2.1
orbs:
  android: circleci/android@0.2.1

jobs:
  # beta-ios:
  #   macos:
  #     xcode: 14.0.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run the script for beta iOS
  #         command: |
  #           bash scripts/prepare-flutter.sh
  #           bash scripts/prepare-ios.sh
  #           bash scripts/beta-ios.sh

  beta-android:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run:
          name: Install Dependencies and Build APK
          command: |
            flutter pub get
            flutter build apk --release
      - run:
          name: Rename and Move APK
          command: |
            # Get the current date in YYYY-MM-DD format
            CURRENT_DATE=$(date +"%Y-%m-%d")
            # Source and destination paths
            SOURCE_APK_PATH=/home/ibn/Hubb/task_/build/app/outputs/flutter-apk/app-release.apk
            DESTINATION_DIR=/path/to/destination/directory

            # Rename the APK file with the current date
            RENAMED_APK_PATH=$DESTINATION_DIR/app-release-$CURRENT_DATE.apk
            mv $SOURCE_APK_PATH $RENAMED_APK_PATH

            # Print the renamed APK path
            echo "Renamed APK path: $RENAMED_APK_PATH"      

      - run:
          name: Run the script for beta Android
          command: bash scripts/beta-android.sh

workflows:
  build-test-adhoc:
    jobs:
      - beta-android
      # - beta-ios
