# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    macos:
      xcode: 14.0.1
 
    steps:
      - checkout
      - run : echo "I Work Fine With Circle CI"


 

workflows:
  build-test-adhoc:
    jobs:
      - try-job

